apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: deployment-name
spec:
  replicas: 1
  template:
    metadata:
      labels:
        label-key: label-value
    spec:
      containers:
        - name: deploment-container-name
          image: webfw20:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
