export interface UserToken {
    access_token: string;
    token_type: string;
    refresh_token: string;
    expires_in: number;
    scope: string;
    userInfo: {
        userData: {
            userId: number,
            userRight: null,
            userName: string,
            password: string,
            status: any,
            email: null,
            cellphone: null,
            telephone: null,
            gender: null,
            lastChangePassword: null,
            loginFailureCount: null,
            identityCard: null,
            fullName: '',
            userTypeId: null,
            createDate: null,
            locationId: null,
            passwordChanged: null,
            lastLogin: null,
            profileId: null,
            lastResetPassword: null,
            ip: null,
            deptId: null,
            posId: null,
            deptName: null,
            ignoreCheckIp: null,
            lastValidTime: null,
            checkIpLan: null,
            tempLockCount: null,
            loginFailAllow: null,
            temporaryLockTime: null,
            maxTmpLockAday: null,
            passwordValidTime: null,
            userValidTime: null,
            allowMultiIpLogin: null,
            allowIp: null,
            allowLoginTimeStart: null,
            allowLoginTimeEnd: null,
            id: null,
            name: null,
            needChangePassword: null,
            timeToChangePassword: null,
            checkId: null,
            ipLan: null,
            checkIp: null,
            timeToPasswordExpire: null,
            usePermission: null,
            useVisibility: null
        },
        roles: [],
        items: []
    };
    jti?: string;
}
